import { EventEmitter } from 'node:events';
import type { Alert, CommandAction, CommandRecord, HouseState, Limit, TargetType } from './types.js';

const now = () => new Date().toISOString();
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const cityIds = ['el-amal', 'ennasr', 'carthage', 'el-wifak', 'jardin'];

export class SimulationStore extends EventEmitter {
  houses: HouseState[] = []; commands: CommandRecord[] = []; alerts: Alert[] = []; cityLimits = new Map<string, Limit>(); districtLimits = new Map<string, Limit>(); centralLimits = new Map<string, Limit>(); paused = false; speed = 1; failureRate = 0.05; scenario = 'Normal Day';
  constructor() { super(); this.reset(); }
  reset() { this.houses = Array.from({ length: 240 }, (_, i) => { const number = 1245 + i; const pv = i % 4 === 0; const offline = i !== 0 && i % 47 === 0; const natural = i === 0 ? 5.2 : Number((2.8 + (i * .37) % 6.4).toFixed(2)); return { id: `M-${String(number).padStart(6, '0')}`, cityId: cityIds[i % cityIds.length], districtId: 'tunis-nord', centralId: 'centrale-tunis', meterId: `SM-${String(number).padStart(6, '0')}`, hasPv: pv, naturalDemandKw: natural, effectiveDemandKw: offline ? 0 : natural, pvKw: pv ? (i === 0 ? 5.8 : Number((1.2 + (i * .29) % 5.8).toFixed(2))) : 0, status: offline ? 'Offline' : 'Online', voltage: offline ? 0 : 231, current: offline ? 0 : Number((natural * 4.35).toFixed(1)), lastCommunication: offline ? 'Communication lost' : 'Just now' }; }); this.commands = []; this.alerts = []; this.cityLimits.clear(); this.districtLimits.clear(); this.centralLimits.clear(); this.emitState(); }
  private limitsFor(house: HouseState): number[] { return [house.powerLimitKw, this.cityLimits.get(house.cityId)?.value, this.districtLimits.get(house.districtId)?.value, this.centralLimits.get(house.centralId)?.value].filter((x): x is number => x !== undefined); }
  private applyEffective() { const expired = Date.now(); this.houses.forEach(h => { if (h.limitExpiresAt && h.limitExpiresAt <= expired) { h.powerLimitKw = undefined; h.limitExpiresAt = undefined; this.alerts.unshift({ id: id('ALT'), timestamp: now(), target: h.id, level: 'MEDIUM', message: 'Power limit expired; natural demand restored' }); } if (h.status === 'Offline') { h.effectiveDemandKw = 0; return; } const direct = Math.min(h.naturalDemandKw, ...this.limitsFor(h)); h.effectiveDemandKw = Number(direct.toFixed(2)); h.current = Number((direct * 4.35).toFixed(1)); h.status = h.powerLimitKw && h.naturalDemandKw > h.powerLimitKw ? 'Limited' : 'Online'; }); this.applyAggregateLimits(this.cityLimits, h => h.cityId); this.applyAggregateLimits(this.districtLimits, h => h.districtId); this.applyAggregateLimits(this.centralLimits, h => h.centralId); }
  private applyAggregateLimits(limits: Map<string, Limit>, key: (h: HouseState) => string) { for (const [asset, limit] of limits) { const group = this.houses.filter(h => key(h) === asset && h.status !== 'Offline'); const total = group.reduce((s, h) => s + h.effectiveDemandKw, 0); if (total > limit.value) { const factor = limit.value / total; group.forEach(h => { h.effectiveDemandKw = Number((h.effectiveDemandKw * factor).toFixed(2)); h.current = Number((h.effectiveDemandKw * 4.35).toFixed(1)); h.status = 'Limited'; }); } } }
  tick() { if (this.paused) return; const boost = this.scenario === 'Peak Demand' || this.scenario === 'Evening Peak' ? 1.35 : 1; const solar = this.scenario === 'High Solar' ? 1.45 : this.scenario === 'Low Solar' ? .45 : 1; const time = Date.now(); this.houses.forEach((h, i) => { if (h.status !== 'Offline') { h.naturalDemandKw = Number(Math.max(.4, h.naturalDemandKw + Math.sin(time / 3000 + i) * .12 * boost).toFixed(2)); if (h.hasPv) h.pvKw = Number(Math.max(0, h.pvKw + Math.sin(time / 5000 + i) * .08 * solar).toFixed(2)); h.voltage = Number((230 + Math.sin(time / 7000 + i) * 1.8).toFixed(1)); h.lastCommunication = 'Just now'; } }); this.applyEffective(); this.emitState(); }
  aggregate(filter: (h: HouseState) => boolean = () => true) { const selected = this.houses.filter(filter); const online = selected.filter(h => h.status !== 'Offline'); const naturalDemandKw = online.reduce((s, h) => s + h.naturalDemandKw, 0); const effectiveDemandKw = online.reduce((s, h) => s + h.effectiveDemandKw, 0); const pvKw = online.reduce((s, h) => s + h.pvKw, 0); return { houses: selected.length, online: online.length, offline: selected.length - online.length, naturalDemandKw, effectiveDemandKw, pvKw, gridImportKw: Math.max(0, effectiveDemandKw - pvKw), gridExportKw: Math.max(0, pvKw - effectiveDemandKw) }; }
  snapshot() { return { simulation: { paused: this.paused, speed: this.speed, failureRate: this.failureRate, scenario: this.scenario }, global: this.aggregate(), cities: cityIds.map(cityId => ({ cityId, ...this.aggregate(h => h.cityId === cityId), limit: this.cityLimits.get(cityId) })), district: { districtId: 'tunis-nord', ...this.aggregate(h => h.districtId === 'tunis-nord'), limit: this.districtLimits.get('tunis-nord') }, central: { centralId: 'centrale-tunis', ...this.aggregate(h => h.centralId === 'centrale-tunis'), limit: this.centralLimits.get('centrale-tunis') }, alerts: this.alerts.slice(0, 100), commands: this.commands.slice(0, 200) }; }
  private emitState() { this.emit('state', this.snapshot()); }
  async command(input: { targetType: TargetType; targetId: string; action: CommandAction; value?: number; durationMinutes?: number; user?: string }): Promise<CommandRecord> { const command: CommandRecord = { commandId: id('CMD'), timestamp: now(), user: input.user ?? 'Operator', targetType: input.targetType, targetId: input.targetId, commandType: input.action, requestedValue: input.value, status: 'PENDING', result: 'Queued' }; this.commands.unshift(command); this.emit('command', command); await wait(300 + Math.random() * 900); command.status = 'SENDING'; command.result = 'Sending command…'; this.emit('command', command); await wait(220); if (Math.random() < this.failureRate) { command.status = 'FAILED'; command.result = 'Simulated communication failure; target state unchanged'; this.emit('command', command); return command; } command.status = 'ACCEPTED'; command.result = 'Command accepted'; this.emit('command', command); await wait(220); this.applyCommand(input, command); command.status = 'APPLIED'; this.emit('command', command); this.emitState(); return command; }
  private applyCommand(input: { targetType: TargetType; targetId: string; action: CommandAction; value?: number; durationMinutes?: number }, command: CommandRecord) { const house = this.houses.find(h => h.id === input.targetId); if (input.action === 'setPowerLimit' && input.value && house) { command.previousValue = house.powerLimitKw ?? 'No limit'; house.powerLimitKw = input.value; house.limitExpiresAt = input.durationMinutes ? Date.now() + input.durationMinutes * 60000 : undefined; command.newValue = `${input.value} kW`; command.result = `Applied house power limit: ${input.value} kW`; if (house.naturalDemandKw > input.value) this.alerts.unshift({ id: id('ALT'), timestamp: now(), target: house.id, level: 'MEDIUM', message: `Power limit reached; effective power limited to ${input.value} kW` }); }
    else if (input.action === 'removePowerLimit' && house) { command.previousValue = house.powerLimitKw ?? 'No limit'; house.powerLimitKw = undefined; house.limitExpiresAt = undefined; command.newValue = 'No limit'; command.result = 'Power limit removed'; }
    else if ((input.action === 'disconnect' || input.action === 'reconnect') && house) { const online = input.action === 'reconnect'; house.status = online ? 'Online' : 'Offline'; house.lastCommunication = online ? 'Just now' : 'Communication lost'; house.voltage = online ? 231 : 0; command.result = online ? 'Meter reconnected' : 'Meter disconnected'; if (!online) this.alerts.unshift({ id: id('ALT'), timestamp: now(), target: house.id, level: 'HIGH', message: 'Meter communication lost' }); }
    else if (input.action === 'remoteRead' && house) { house.lastCommunication = 'Just now'; command.result = `Read received: ${house.voltage} V, ${house.current} A, ${house.effectiveDemandKw} kW`; }
    else if (input.action === 'diagnostics') command.result = 'Diagnostic complete: communication OK, voltage normal, meter healthy';
    else if (input.action === 'setPowerLimit' && input.value) { const map = input.targetType === 'city' ? this.cityLimits : input.targetType === 'district' ? this.districtLimits : this.centralLimits; map.set(input.targetId, { value: input.value, expiresAt: input.durationMinutes ? Date.now() + input.durationMinutes * 60000 : undefined }); command.newValue = `${input.value} kW`; command.result = `Applied ${input.targetType} aggregate limit: ${input.value} kW`; }
    else command.result = 'Simulation command applied'; this.applyEffective(); }
}
const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
