import { useEffect, useMemo, useState } from 'react';
import { Activity, Bell, Bolt, Building2, CircleAlert, House, Map, PanelLeft, Radio, Sun, Zap } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { plants, pvPlants } from './data/mockData';
import type { Page, RuntimeHouse } from './types';
import { balance } from './utils/energyCalculations';
import { aggregates, createSimulation, removeHouseLimit, setHouseLimit, setMeterStatus, tick, type SimulationState } from './services/simulationEngine';

const nav: Array<{ label: string; page?: Page }> = [{ label: 'Overview', page: 'overview' }, { label: 'Infrastructure' }, { label: 'Centrales', page: 'centrals' }, { label: 'Districts', page: 'district' }, { label: 'Cités', page: 'city' }, { label: 'Maisons', page: 'houses' }, { label: 'Energy' }, { label: 'Solar', page: 'solar' }, { label: 'Grid Map', page: 'map' }, { label: 'Operations' }, { label: 'Alerts', page: 'alerts' }, { label: 'Operations Log', page: 'operations' }];
const commands = ['Request Status', 'Remote Read', 'Diagnostics', 'Synchronize', 'Configuration', 'Set Power Limit', 'Reconnect', 'Disconnect', 'Reset Meter'];
type SimulationResult = { target: string; command: string; title: string; lines: string[]; timestamp: string };

function responseFor(target: string, command: string, time: string): SimulationResult {
  const common = { target, command, timestamp: time };
  switch (command) {
    case 'Request Status': return { ...common, title: 'Asset status received', lines: ['Communication: Online', 'Operating state: Normal', 'Availability: 98.4%', 'Last heartbeat: Just now'] };
    case 'Remote Read': return { ...common, title: 'Meter reading complete', lines: ['Voltage: 231 V', 'Current: 8.4 A', 'Active power: 4.2 kW', 'Import: 18.4 kWh · Export: 7.2 kWh'] };
    case 'Diagnostics': return { ...common, title: 'Diagnostics complete', lines: ['Communication link: Passed', 'Measurement integrity: Passed', 'No critical fault detected', 'Recommendation: continue monitoring'] };
    case 'Synchronize': return { ...common, title: 'Synchronization complete', lines: ['Time profile synchronized', 'Meter profile version: 2.4.1', 'Data packets reconciled', 'Result: Success'] };
    case 'Configuration': return { ...common, title: 'Configuration simulated', lines: ['Tariff profile: Residential standard', 'Read interval: 15 minutes', 'Remote configuration validated', 'No real configuration changed'] };
    case 'Load Limit': return { ...common, title: 'Load limit simulation active', lines: ['Requested limit: 3.5 kW', 'Policy: temporary peak reduction', 'Affected service remains connected', 'No real limit applied'] };
    case 'Reconnect': return { ...common, title: 'Service reconnection simulated', lines: ['Relay state: Closed', 'Communication: Online', 'Supply status: Restored', 'No real relay action performed'] };
    case 'Disconnect': return { ...common, title: 'Service disconnection simulated', lines: ['Relay state: Open (simulated)', 'Supply status: Isolated in simulation', 'Safety confirmation: acknowledged', 'No real relay action performed'] };
    case 'Reset': return { ...common, title: 'Equipment reset simulated', lines: ['Session cache cleared', 'Communication service restarted', 'Asset status: recovering', 'No real equipment reset performed'] };
    default: return { ...common, title: 'Simulation complete', lines: ['Command accepted', 'No real grid action performed'] };
  }
}

function Card({ label, value, hint = 'Live data' }: { label: string; value: string; hint?: string }) { return <article className="card"><span>{label}</span><strong>{value}</strong><small>↗ {hint}</small></article>; }
function Header({ onMenu }: { onMenu: () => void }) { const [now, setNow] = useState(new Date()); useEffect(() => { const id = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(id); }, []); return <header><button className="icon mobile" onClick={onMenu}><PanelLeft size={18} /></button><div className="search">Search assets, meters, districts…</div><div className="live"><i /> LIVE SIMULATION</div><span className="demo">DEMO / SIMULATION</span><time>{now.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' })}</time><Bell size={17} /><span>Operator</span></header>; }
function Breadcrumb({ page, go }: { page: Page; go: (p: Page) => void }) { const steps: Partial<Record<Page, string[]>> = { central: ['Centrale Tunis'], district: ['Centrale Tunis', 'District Tunis Nord'], city: ['Centrale Tunis', 'District Tunis Nord', 'Cité El Amal'], house: ['Centrale Tunis', 'District Tunis Nord', 'Cité El Amal', 'Maison M-001245'], meter: ['Centrale Tunis', 'District Tunis Nord', 'Cité El Amal', 'Maison M-001245', 'Smart Meter SM-001245'] }; return <div className="crumb"><button onClick={() => go('overview')}>Overview</button>{(steps[page] ?? [page[0].toUpperCase() + page.slice(1)]).map((x, i) => <span key={x}> / {i < 3 ? <button onClick={() => go((['central', 'district', 'city'] as Page[])[i])}>{x}</button> : x}</span>)}</div>; }
function Chart({ data = [] }: { data?: { hour: string; production: number; consumption: number }[] }) { return <ResponsiveContainer width="100%" height={245}><AreaChart data={data}><defs><linearGradient id="p" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#2ed3c6" stopOpacity=".6" /><stop offset="1" stopColor="#2ed3c6" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="#193741" vertical={false} /><XAxis dataKey="hour" hide /><YAxis hide /><Tooltip contentStyle={{ background: '#102631', border: '1px solid #2b4e5a', borderRadius: 7 }} /><Area dataKey="production" stroke="#2ed3c6" fill="url(#p)" strokeWidth={2} /><Area dataKey="consumption" stroke="#ffc45a" fill="none" strokeWidth={2} /></AreaChart></ResponsiveContainer>; }
function Controls({ target, affected = 1, ask }: { target: string; affected?: number; ask: (target: string, command: string, affected: number) => void }) { return <><div className="controls">{commands.map(c => <button key={c} onClick={() => ask(target, c, affected)}>{c}</button>)}</div><p className="muted">Simulation only — no real grid action.</p></>; }
function AlertRows() { return <>{[['CRITICAL', 'Communication loss', 'SM-001248 · Cité Ennasr'], ['HIGH', 'Inverter fault', 'PV Centrale Sud · 12 min ago'], ['MEDIUM', 'High consumption', 'District Tunis Nord']].map(([level, label, meta]) => <div className="alert" key={label}><b className={level.toLowerCase()}>{level}</b><div><strong>{label}</strong><small>{meta}</small></div></div>)}</>; }
function HouseTable({ go, rows = [] }: { go: (page: Page, index?: number) => void; rows?: RuntimeHouse[] }) { return <div className="table-scroll"><table><thead><tr><th>House</th><th>City</th><th>Meter</th><th>PV</th><th>Consumption</th><th>PV prod.</th><th>Import</th><th>Export</th><th>Status</th></tr></thead><tbody>{rows.map((h, i) => { const e = balance(h.consumption, h.pv); return <tr onClick={() => go('house', i)} key={h.id}><td><strong>{h.id}</strong>{h.powerLimitKw && <small className="limited">LIMIT {h.powerLimitKw} kW</small>}</td><td>{h.city}</td><td>{h.meter}</td><td>{h.solar ? '☀ Yes' : '—'}</td><td>{h.consumption.toFixed(1)} kW</td><td>{h.pv.toFixed(1)} kW</td><td>{e.gridImport.toFixed(1)} kW</td><td>{e.gridExport.toFixed(1)} kW</td><td className={h.status === 'Online' ? 'online' : 'offline'}>● {h.powerLimitKw ? 'Limited' : h.status}</td></tr>; })}</tbody></table></div>; }

export default function App() {
  const [page, setPage] = useState<Page>('overview'); const [selectedHouse, setSelectedHouse] = useState(0); const [menu, setMenu] = useState(false); const [simulation, setSimulation] = useState<SimulationState>(createSimulation); const [pending, setPending] = useState<{ target: string; command: string; affected: number } | null>(null); const [limitTarget, setLimitTarget] = useState<string | null>(null); const [limitValue, setLimitValue] = useState('3.0'); const [limitDuration, setLimitDuration] = useState('30'); const [toast, setToast] = useState(''); const [lastResult, setLastResult] = useState<SimulationResult | null>(null);
  useEffect(() => { const id = window.setInterval(() => setSimulation(tick), 1000); return () => window.clearInterval(id); }, []);
  const go = (next: Page, index = 0) => { if (next === 'house') setSelectedHouse(index); setPage(next); setMenu(false); };
  const ask = (target: string, command: string, affected: number) => { if (command === 'Set Power Limit' && target.startsWith('House ')) { const id = target.replace('House ', ''); const value = window.prompt(`POWER LIMIT CONTROL\nTarget: ${id}\nEnter a new limit in kW`, limitValue); if (value === null) return; const limit = Number(value); if (!Number.isFinite(limit) || limit <= 0) { window.alert('Enter a power limit greater than 0 kW.'); return; } const duration = window.prompt('Duration in minutes (leave empty for Until removed)', limitDuration); const seconds = duration ? Number(duration) * 60 : undefined; setSimulation(s => setHouseLimit(s, id, limit, seconds)); setLastResult(responseFor(target, 'SET_POWER_LIMIT', new Date().toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit', second: '2-digit' }))); return; } setPending({ target, command, affected }); };
  const confirm = () => { if (!pending) return; const time = new Date().toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' }); const result = responseFor(pending.target, pending.command, time); if (pending.command === 'Disconnect') setSimulation(s => setMeterStatus(s, pending.target.replace('House ', '').replace('Smart Meter ', '').replace('SM-', 'M-'), false)); else if (pending.command === 'Reconnect') setSimulation(s => setMeterStatus(s, pending.target.replace('House ', '').replace('Smart Meter ', '').replace('SM-', 'M-'), true)); else setSimulation(s => ({ ...s, commandStatus: result.title, operations: [{ time, user: 'Operator', target: pending.target, command: pending.command, status: 'Success' }, ...s.operations] })); setLastResult(result); setToast(`${pending.command} completed successfully. Simulation only.`); const wasRead = pending.command === 'Remote Read'; setPending(null); if (wasRead) setPage('meter'); setTimeout(() => setToast(''), 3600); };
  const applyLimit = () => { if (!limitTarget) return; const limit = Number(limitValue); if (!Number.isFinite(limit) || limit <= 0) return; const seconds = limitDuration === 'until' ? undefined : Number(limitDuration) * 60; setSimulation(s => setHouseLimit(s, limitTarget, limit, seconds)); setLastResult(responseFor(`House ${limitTarget}`, 'SET_POWER_LIMIT', new Date().toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit', second: '2-digit' }))); setLimitTarget(null); };
  const house = simulation.houses[selectedHouse] ?? simulation.houses[0]; const energy = useMemo(() => balance(house.consumption, house.pv), [house]); const grid = aggregates(simulation);
  const title = { overview: 'Energy Command Center', centrals: 'Power Plants', central: 'Centrale Tunis', district: 'District Tunis Nord', city: 'Cité El Amal', houses: 'Houses', house: `House ${house.id}`, meter: 'Smart Meter SM-001245', solar: 'Solar Energy', map: 'Grid Map', alerts: 'Alert Center', operations: 'Operations Log' }[page];
  let body: React.ReactNode;
  if (page === 'overview') body = <><section className="simulation-toolbar"><b>LIVE SIMULATION ●</b><button onClick={() => setSimulation(s => ({ ...s, paused: !s.paused }))}>{simulation.paused ? 'Resume' : 'Pause'}</button>{([1, 2, 5] as const).map(speed => <button className={simulation.speed === speed ? 'selected' : ''} onClick={() => setSimulation(s => ({ ...s, speed }))} key={speed}>{speed}x</button>)}<span>Scenario: {simulation.scenario}</span><select value={simulation.scenario} onChange={e => setSimulation(s => ({ ...s, scenario: e.target.value }))}><option>Normal Day</option><option>Peak Demand</option><option>High Solar</option><option>Low Solar</option><option>Evening Peak</option></select><button onClick={() => { if (window.confirm('Reset all simulation states?')) setSimulation(createSimulation()); }}>Reset Simulation</button></section><section className="kpis">{[['Centrales', '5'], ['Districts', '15'], ['Houses', String(simulation.houses.length)], ['Meters Online', String(grid.online)], ['Meters Offline', String(grid.offline)], ['Power Limited', String(grid.limited)], ['PV Production', `${grid.pv.toFixed(1)} kW`], ['Consumption', `${grid.demand.toFixed(1)} kW`], ['Grid Import', `${grid.gridImport.toFixed(1)} kW`], ['Grid Export', `${grid.gridExport.toFixed(1)} kW`]].map(x => <Card key={x[0]} label={x[0]} value={x[1]} />)}</section><section className="grid"><article className="panel wide"><PanelHead title="Live production vs consumption" /><Chart data={simulation.chart} /><div className="legend"><span>● Production</span><span>● Consumption</span></div></article><article className="panel"><PanelHead title={`Live alerts · ${simulation.alerts.length + 3}`} />{simulation.alerts.slice(0, 4).map(a => <div className="alert" key={a.id}><b className="medium">{a.level}</b><div><strong>{a.message}</strong><small>{a.target} · {a.time}</small></div></div>)}<AlertRows /></article><article className="panel wide"><PanelHead title="Global Energy Flow" /><div className="flow"><Flow icon={<Sun />} name="PV GENERATION" value={`${grid.pv.toFixed(1)} kW`} /><em>→</em><Flow icon={<Bolt />} name="HOUSES" value={`${grid.demand.toFixed(1)} kW`} /><em>→</em><Flow icon={<Radio />} name="STEG GRID" value={`${grid.gridImport.toFixed(1)} kW import`} /></div></article></section></>;
  else if (page === 'centrals') body = <><article className="panel"><table><thead><tr><th>Name</th><th>Type</th><th>Current power</th><th>Availability</th><th>Status</th></tr></thead><tbody>{plants.map(p => <tr key={p.name} onClick={() => go('central')}><td><strong>{p.name}</strong></td><td>{p.type}</td><td>{p.power}</td><td>{p.availability}</td><td className="online">● Operational</td></tr>)}</tbody></table></article><section className="grid"><article className="panel wide"><PanelHead title="Generation history" /><Chart /></article><article className="panel"><PanelHead title="Central Remote Control" /><Controls target="Centrale Tunis" ask={ask} /></article></section></>;
  else if (page === 'central') body = <><section className="kpis">{[['Installed power', '180 MW'], ['Current power', '148 MW'], ['Availability', '94%'], ['Daily generation', '2.4 GWh'], ['Active alerts', '1']].map(x => <Card key={x[0]} label={x[0]} value={x[1]} />)}</section><section className="grid"><article className="panel wide"><PanelHead title="Generation history" /><Chart /></article><article className="panel"><PanelHead title="Central Remote Control" /><Controls target="Centrale Tunis" ask={ask} /></article></section><article className="panel"><PanelHead title="Associated districts" /><table><tbody><tr onClick={() => go('district')}><td><strong>District Tunis Nord</strong></td><td>42.6 MW consumption</td><td className="online">● Healthy</td></tr><tr><td><strong>District Tunis Centre</strong></td><td>38.1 MW consumption</td><td className="online">● Healthy</td></tr></tbody></table></article></>;
  else if (page === 'district') body = <><section className="kpis">{[['Consumption', '42.6 MW'], ['Local PV', '8.3 MW'], ['STEG Import', '29.4 MW'], ['Cités', '4'], ['Alerts', '3']].map(x => <Card key={x[0]} label={x[0]} value={x[1]} />)}</section><section className="grid"><article className="panel wide"><PanelHead title="District load" /><Chart /></article><article className="panel"><PanelHead title="District Remote Control" /><Controls target="District Tunis Nord" affected={3240} ask={ask} /></article></section><article className="panel"><PanelHead title="Cités" /><table><tbody><tr onClick={() => go('city')}><td><strong>Cité El Amal</strong></td><td>850 meters</td><td>12.2 MW</td><td className="online">● Normal</td></tr><tr><td><strong>Cité Ennasr</strong></td><td>720 meters</td><td>10.9 MW</td><td className="offline">● Attention</td></tr></tbody></table></article></>;
  else if (page === 'city') body = <><section className="kpis">{[['Houses', String(simulation.houses.filter(h => h.city === 'Cité El Amal').length)], ['PV houses', String(simulation.houses.filter(h => h.city === 'Cité El Amal' && h.solar).length)], ['Consumption', `${simulation.houses.filter(h => h.city === 'Cité El Amal').reduce((s, h) => s + h.consumption, 0).toFixed(1)} kW`], ['PV production', `${simulation.houses.filter(h => h.city === 'Cité El Amal').reduce((s, h) => s + h.pv, 0).toFixed(1)} kW`], ['Alerts', String(simulation.alerts.length)]].map(x => <Card key={x[0]} label={x[0]} value={x[1]} />)}</section><section className="grid"><article className="panel wide"><PanelHead title="Local grid map" /><MapCanvas click={() => go('house')} /></article><article className="panel"><PanelHead title="City Remote Operations" /><Controls target="Cité El Amal" affected={simulation.houses.filter(h => h.city === 'Cité El Amal').length} ask={ask} /></article></section><article className="panel"><PanelHead title="Houses" /><HouseTable go={go} rows={simulation.houses.filter(h => h.city === 'Cité El Amal')} /></article></>;
  else if (page === 'houses') body = <><div className="filters">{['All houses', 'PV', 'Online', 'Offline', 'High consumption', 'Alerts'].map(x => <button key={x}>{x}</button>)}</div><article className="panel"><HouseTable go={go} rows={simulation.houses} /></article></>;
  else if (page === 'house') body = <><section className="kpis">{[['Natural Demand', `${house.naturalDemand.toFixed(1)} kW`], ['Effective Consumption', `${house.consumption.toFixed(1)} kW`], ['PV Production', `${house.pv.toFixed(1)} kW`], ['Grid Import', `${energy.gridImport.toFixed(1)} kW`], ['Grid Export', `${energy.gridExport.toFixed(1)} kW`]].map(x => <Card key={x[0]} label={x[0]} value={x[1]} />)}</section><section className="grid"><article className="panel wide"><PanelHead title="Current Energy Flow" /><div className="flow"><Flow icon={<Sun />} name={house.solar ? 'SOLAR PV' : 'STEG GRID'} value={`${house.solar ? house.pv.toFixed(1) : energy.gridImport.toFixed(1)} kW`} /><em>→</em><Flow icon={<House />} name="HOUSE" value={`${house.consumption.toFixed(1)} kW`} /><em>{energy.gridExport ? '→' : '←'}</em><Flow icon={<Radio />} name="STEG GRID" value={energy.gridExport ? `${energy.gridExport.toFixed(1)} kW export` : `${energy.gridImport.toFixed(1)} kW import`} /></div>{house.powerLimitKw && <div className="limit-status"><b>POWER LIMIT ACTIVE</b><strong>{house.powerLimitKw.toFixed(1)} kW LIMIT</strong><div><i style={{ width: `${Math.min(100, house.consumption / house.powerLimitKw * 100)}%` }} /></div><span>Current {house.consumption.toFixed(1)} kW · Available {Math.max(0, house.powerLimitKw - house.consumption).toFixed(1)} kW</span></div>}</article><article className="panel"><PanelHead title="House Remote Control" /><p className="muted">{house.status} · Current power {house.consumption.toFixed(1)} kW · {house.powerLimitKw ? `Limit ${house.powerLimitKw.toFixed(1)} kW` : 'No limit'}</p><div className="controls"><button onClick={() => ask(`House ${house.id}`, 'Remote Read', 1)}>Remote Read</button><button onClick={() => ask(`House ${house.id}`, 'Diagnostics', 1)}>Diagnostics</button><button onClick={() => ask(`House ${house.id}`, 'Set Power Limit', 1)}>Set Power Limit</button>{house.powerLimitKw && <button onClick={() => setSimulation(s => removeHouseLimit(s, house.id))}>Remove Power Limit</button>}<button onClick={() => ask(`House ${house.id}`, 'Reconnect', 1)}>Reconnect</button><button onClick={() => ask(`House ${house.id}`, 'Disconnect', 1)}>Disconnect</button><button onClick={() => ask(`House ${house.id}`, 'Reset Meter', 1)}>Reset Meter</button></div><p className="muted">Capabilities: Remote Read ✓ · Diagnostics ✓ · Power Limit ✓ · Disconnect ✓</p></article></section><article className="panel"><PanelHead title="Recent Commands" /><table><tbody>{simulation.operations.filter(x => x.target.includes(house.id)).slice(0, 5).map((o, i) => <tr key={i}><td>{o.time}</td><td>{o.command}</td><td className="online">Applied</td></tr>)}</tbody></table></article></>;
  else if (page === 'meter') body = <><section className="kpis">{[['Status', 'Online'], ['Voltage', '231 V'], ['Current', '8.4 A'], ['Active power', '4.2 kW'], ['Frequency', '50.0 Hz']].map(x => <Card key={x[0]} label={x[0]} value={x[1]} />)}</section><section className="grid"><article className="panel wide"><PanelHead title="Energy measurements" /><div className="mini"><Card label="Import Energy" value="18.4 kWh" /><Card label="Export Energy" value="7.2 kWh" /><Card label="Monthly Energy" value="387 kWh" /></div><p className="muted">Prototype / Simulation / À valider avec STEG</p></article><article className="panel"><PanelHead title="Remote meter reading" /><p className="muted">All communication is simulated. No real grid action.</p><button className="primary" onClick={() => ask('Smart Meter SM-001245', 'Remote Read', 1)}>READ NOW</button><h3>Meter controls</h3><Controls target="Smart Meter SM-001245" ask={ask} /></article></section></>;
  else if (page === 'solar') body = <><section className="kpis">{[['Installed PV', '94 MWp'], ['Current generation', '63.3 MW'], ['Daily generation', '488 MWh'], ['Monthly generation', '10.8 GWh'], ['Grid export', '14 MW']].map(x => <Card key={x[0]} label={x[0]} value={x[1]} />)}</section><section className="grid"><article className="panel wide"><PanelHead title="PV generation — 24H" /><Chart /></article><article className="panel"><PanelHead title="Solar plants" />{pvPlants.map(p => <div className="alert" key={p.name}><b className="medium">PV</b><div><strong>{p.name}</strong><small>{p.capacity} installed · {p.power} current · {p.yield} yield</small></div></div>)}</article></section></>;
  else if (page === 'map') body = <><div className="filters"><button>All assets</button><button>Solar Assets</button><button>Houses</button><button>Alerts</button></div><article className="panel"><MapCanvas click={() => go('house')} /><p className="muted">GIS simulation — click a house marker to inspect it. Coordinates and data are fictitious.</p></article></>;
  else if (page === 'alerts') body = <><div className="filters"><button>All levels</button><button>Critical</button><button>High</button><button>Open</button></div><article className="panel"><AlertRows /><div className="alert"><b className="medium">MEDIUM</b><div><strong>Voltage anomaly</strong><small>House M-001203 · District Tunis Centre</small></div></div></article></>;
  else body = <article className="panel"><div className="table-scroll"><table><thead><tr><th>Time</th><th>User</th><th>Target</th><th>Command</th><th>Status</th><th>Response</th></tr></thead><tbody>{simulation.operations.map((o, i) => <tr key={`${o.time}-${i}`}><td>{o.time}</td><td>{o.user}</td><td>{o.target}</td><td>{o.command}</td><td className="online">● {o.status}</td><td>Simulation command — no real grid action</td></tr>)}</tbody></table></div></article>;
  return <div className="app"><aside className={menu ? 'open' : ''}><div className="brand"><Zap /> CITYOS <small>SMART ENERGY</small></div><nav>{nav.map(x => x.page ? <button className={page === x.page ? 'active' : ''} key={x.label} onClick={() => go(x.page!)}>{x.label}</button> : <p key={x.label}>{x.label}</p>)}</nav></aside><main><Header onMenu={() => setMenu(!menu)} /><div className="content"><Breadcrumb page={page} go={go} /><div className="title"><div><h1>{title}</h1><p>{page === 'overview' ? 'Vue globale du réseau CITYOS' : 'Supervision énergétique simulée'}</p></div>{page === 'house' && <button className="primary" onClick={() => go('meter')}>Open Smart Meter</button>}</div>{body}{lastResult && <article className="panel simulation-result"><div><span className="result-eyebrow">LAST SIMULATION RESULT · {lastResult.timestamp}</span><h2>{lastResult.title}</h2><p className="muted">{lastResult.command} · {lastResult.target}</p><ul>{lastResult.lines.map(line => <li key={line}>{line}</li>)}</ul></div><button onClick={() => setLastResult(null)}>Dismiss</button></article>}</div></main>{pending && <div className="overlay"><section className="dialog"><CircleAlert color="#ffc45a" /><h2>Confirm simulation</h2><p>You are about to simulate “{pending.command}” for {pending.target}. This action will affect {pending.affected.toLocaleString('fr-FR')} meter{pending.affected === 1 ? '' : 's'}. No real grid action will be performed.</p><button onClick={() => setPending(null)}>Cancel</button><button className="primary" onClick={confirm}>Confirm Simulation</button></section></div>}{toast && <div className="toast">{toast}</div>}</div>;
}
function PanelHead({ title }: { title: string }) { return <h2>{title}</h2>; } function Flow({ icon, name, value }: { icon: React.ReactNode; name: string; value: string }) { return <div className="flow-node">{icon}<span>{name}</span><strong>{value}</strong></div>; } function MapCanvas({ click }: { click: () => void }) { return <div className="map-canvas"><span className="map-label">TUNISIE — DONNÉES SIMULÉES</span><i className="marker plant" /><i className="marker solar" /><i className="marker house" onClick={click} /><i className="marker alert-marker" /></div>; }
