import { chartData, houses, initialOperations } from '../data/mockData';
import type { Command, RuntimeHouse } from '../types';

export type SimulationAlert = { id: string; time: string; target: string; level: 'HIGH' | 'MEDIUM'; message: string };
export type SimulationState = { houses: RuntimeHouse[]; operations: Command[]; alerts: SimulationAlert[]; chart: typeof chartData; paused: boolean; speed: 1 | 2 | 5; failureRate: number; scenario: string; commandStatus: string };
const stamp = () => new Date().toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
const runtime = (h: typeof houses[number]): RuntimeHouse => ({ ...h, naturalDemand: h.consumption, voltage: h.status === 'Online' ? 231 : 0, current: h.status === 'Online' ? Number((h.consumption * 4.35).toFixed(1)) : 0, lastCommunication: 'Just now', limitReached: false });
export const createSimulation = (): SimulationState => ({ houses: houses.map(runtime), operations: initialOperations, alerts: [], chart: chartData, paused: false, speed: 1, failureRate: 5, scenario: 'Normal Day', commandStatus: 'Live state synchronized' });
export const effective = (house: RuntimeHouse) => house.status === 'Offline' ? 0 : Math.min(house.naturalDemand, house.powerLimitKw ?? Infinity);
const record = (state: SimulationState, target: string, command: string, result: string): SimulationState => ({ ...state, commandStatus: result, operations: [{ time: stamp(), user: 'Operator', target, command, status: 'Success' }, ...state.operations] });
export function setHouseLimit(state: SimulationState, id: string, limit: number, durationSeconds?: number): SimulationState { const before = state.houses.find(h => h.id === id); if (!before || limit <= 0) return state; const exceeded = before.naturalDemand > limit; const next = { ...before, powerLimitKw: limit, limitExpiresAt: durationSeconds ? Date.now() + durationSeconds * 1000 : undefined, consumption: Math.min(before.naturalDemand, limit), current: Number((Math.min(before.naturalDemand, limit) * 4.35).toFixed(1)), limitReached: exceeded }; let updated = { ...state, houses: state.houses.map(h => h.id === id ? next : h) }; updated = record(updated, `House ${id}`, 'SET_POWER_LIMIT', `Applied ${limit.toFixed(1)} kW limit`); if (exceeded) updated.alerts = [{ id: `limit-${Date.now()}`, time: stamp(), target: `House ${id}`, level: 'MEDIUM', message: `Demand exceeded configured limit; effective power limited to ${limit.toFixed(1)} kW` }, ...updated.alerts]; return updated; }
export function removeHouseLimit(state: SimulationState, id: string): SimulationState { const updated = state.houses.map(h => h.id === id ? { ...h, powerLimitKw: undefined, limitExpiresAt: undefined, consumption: h.naturalDemand, current: Number((h.naturalDemand * 4.35).toFixed(1)), limitReached: false } : h); return record({ ...state, houses: updated }, `House ${id}`, 'REMOVE_POWER_LIMIT', 'Power limit removed; natural demand restored'); }
export function setMeterStatus(state: SimulationState, id: string, online: boolean): SimulationState { const updated = state.houses.map(h => h.id === id ? { ...h, status: online ? 'Online' as const : 'Offline' as const, consumption: online ? effective(h) : 0, voltage: online ? 231 : 0, current: online ? Number((effective(h) * 4.35).toFixed(1)) : 0, lastCommunication: online ? 'Just now' : 'Communication lost' } : h); let next = record({ ...state, houses: updated }, `House ${id}`, online ? 'RECONNECT_METER' : 'DISCONNECT_METER', online ? 'Meter reconnected and synchronized' : 'Meter disconnected in simulation'); if (!online) next.alerts = [{ id: `offline-${Date.now()}`, time: stamp(), target: `House ${id}`, level: 'HIGH', message: 'Meter communication lost' }, ...next.alerts]; return next; }
export function tick(state: SimulationState): SimulationState { if (state.paused) return state; const now = Date.now(); const expired: string[] = []; const updated = state.houses.map((h, i) => { if (h.status === 'Offline') return h; const multiplier = state.scenario === 'Peak Demand' || state.scenario === 'Evening Peak' ? 1.35 : 1; const solarMultiplier = state.scenario === 'High Solar' ? 1.45 : state.scenario === 'Low Solar' ? .45 : 1; const natural = Number(Math.max(.4, h.naturalDemand + (Math.sin(now / 3000 + i) * .13 * multiplier)).toFixed(2)); const expires = h.limitExpiresAt && h.limitExpiresAt <= now; if (expires) expired.push(h.id); const limit = expires ? undefined : h.powerLimitKw; const consumption = Math.min(natural, limit ?? Infinity); return { ...h, naturalDemand: natural, pv: h.solar ? Number(Math.max(0, h.pv + Math.sin(now / 5000 + i) * .08 * solarMultiplier).toFixed(2)) : 0, powerLimitKw: limit, limitExpiresAt: expires ? undefined : h.limitExpiresAt, consumption: Number(consumption.toFixed(2)), current: Number((consumption * 4.35).toFixed(1)), limitReached: limit !== undefined && natural > limit, voltage: Number((230 + Math.sin(now / 7000 + i) * 1.8).toFixed(1)), lastCommunication: 'Just now' }; }); const total = updated.reduce((sum, h) => sum + h.consumption, 0); const pv = updated.reduce((sum, h) => sum + h.pv, 0); const point = { hour: stamp(), consumption: Number(total.toFixed(1)), production: Number(pv.toFixed(1)) }; const alerts = expired.length ? [{ id: `expired-${now}`, time: stamp(), target: `House ${expired[0]}`, level: 'MEDIUM' as const, message: 'Power limit expired; natural demand restored' }, ...state.alerts] : state.alerts; return { ...state, houses: updated, alerts, chart: [...state.chart.slice(-23), point] }; }
export const aggregates = (state: SimulationState) => { const online = state.houses.filter(h => h.status === 'Online'); const naturalDemand = online.reduce((s, h) => s + h.naturalDemand, 0); const demand = online.reduce((s, h) => s + h.consumption, 0); const pv = online.reduce((s, h) => s + h.pv, 0); return { naturalDemand, demand, pv, gridImport: Math.max(0, demand - pv), gridExport: Math.max(0, pv - demand), online: online.length, offline: state.houses.length - online.length, limited: online.filter(h => h.powerLimitKw !== undefined).length }; };
